[package]
name = "quadrata"
version = "0.1.0"
authors = ["Sean Moore <sean.moore3@mail.mcgill.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"